name: Release Docker Image

# Run when python test runs successfully on master branch
on:
  workflow_run:
    workflows: ["Python Test"]
    branches: ["master"]
    types:
      - completed

jobs:
  docker-build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Package Version
        run: echo "VERSION=`cat pyproject.toml | grep '^version =' | awk '{gsub(/"/, "", $3); print $3}'`" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nikelab222/knockoff-factory:latest,nikelab222/knockoff-factory:${{ env.VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
